version: "3.1"
volumes:
  postgres-data:
    driver: local
  keycloak-realm:
    driver: local
services:
  frontend:
    image: frontend-next
    build: ../client
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_BACKEND_URL=backend:3001
      - NEXTAUTH_SECRET=dDv76XMZxpLcQtHarpWbQRF4tdmIEIO1A3utcJa12n4=
      - KEYCLOAK_ID=myclient
      - KEYCLOAK_SECRET=CM5J5Cy0Jeqx1lgYAZGIMVOl1B8XaSFC
      - KEYCLOAK_ISSUER=http://keycloak:8080/realms/myrealm
    depends_on:
      - backend
  backend:
    image: backend-nest
    build: ../server
    ports:
      - 3001:3001
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/postgres?schema=public
      - KEYCLOAK_BASE_URL="http://keycloak:8080"
      - KEYCLOAK_REALM="myrealm"
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine3.18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8090:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    ports:
      - 8080:8080
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak_password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: ["start-dev", "--import-realm"]
    depends_on:
      - postgres
