version: "3.1"
volumes:
  postgres-data:
    driver: local
  keycloak-realm:
    driver: local
services:
  postgres:
    image: postgres:16-alpine3.18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8090:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    ports:
      - 8080:8080
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak_password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    depends_on:
      - postgres
