import NavBar from "@/components/custom/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}

const Wrapper = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <div className="w-screen h-screen flex justify-center overflow-hidden">
        <div className="w-1/2 h-full">
          <NavBar />
          {children}
        </div>
      </div>
    </>
  );
};
