import NavBar from "src/components/custom/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { ApolloWrapper } from "src/lib/apollo-wrapper";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <Wrapper>{children}</Wrapper>
        </ApolloWrapper>
        <Toaster toastOptions={{ position: "bottom-right", duration: 5000 }} />
      </body>
    </html>
  );
}

const Wrapper = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <div className="w-screen h-screen flex justify-center overflow-hidden">
        <div className="w-1/4 h-full -ml-56">
          <NavBar />
          {children}
        </div>
      </div>
    </>
  );
};
